"""create_bases

Revision ID: 55bc0a969945
Revises: 
Create Date: 2020-11-28 15:55:13.704990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bc0a969945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('start_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talks_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retelling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talks_type_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['talks_type_id'], ['talks_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retelling')
    op.drop_table('talks_type')
    op.drop_table('start_phrases')
    # ### end Alembic commands ###
